apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/metal-ranger-462014-t1/image-registry/auth-ms
        name: auth-ms
        env:
          - name: PORT
            value: "3004"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: jwt_secret
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
status: {}
